AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless URL Shortener (API Gateway + Lambda + DynamoDB)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 128
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: UrlShortenerTable

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  UrlShortenerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UrlShortenerTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: code
          AttributeType: S
      KeySchema:
        - AttributeName: code
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true
  
  CreateShortUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateShortUrlFunction
      Handler: app.create_handler
      CodeUri: src/
      Policies:
        - DynamoDBWritePolicy:
            TableName: UrlShortenerTable
      Events:
        Create:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /shorten
            Method: POST

  ResolveShortUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ResolveShortUrlFunction
      Handler: app.resolve_handler
      CodeUri: src/
      Policies:
        - DynamoDBReadPolicy:
            TableName: UrlShortenerTable
      Events:
        Resolve:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /{code}
            Method: GET
