AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless URL Shortener (API Gateway + Lambda + DynamoDB)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 128
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: UrlShortenerTable

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
